---
name: Config
about: Template Config
title: ''
labels: ''
assignees: Kraevac

---

blank_issues_enabled: false

contact_links:
  - name: 💬 Questions / Install Help
    url: https://github.com/Kraevac/DemonataCore/discussions/categories/download-install-help
    about: Get help installing or updating the mod.

  - name: 📣 Announcements
    url: https://github.com/Kraevac/Demonata-Core/discussions/categories/announcements
    about: Follow releases, patch notes, and news.
